### ISSUE TITLE
Error at choosing printer in sequences.json

### ISSUE THREAD

**Issue by zhampu** [CenterforFuturePublishing/Perpetual-print#2]
When running the program there is an error.
<img width="555" alt="Screenshot 2019-10-15 at 10 56 53" src="https://user-images.githubusercontent.com/10797660/66816634-b4aeb180-ef3a-11e9-8b4d-09c91ae6c1c4.png">

**Comment by prossel** [comment]
Le message est clair. Dois-je vraiment le traduire ?

Le fichier de log donne la liste des imprimantes qui sont disponibles et celle-ci n'en fait visiblement pas partie.

**Comment by zhampu** [comment]
Redemarrer l'ordinateur a rempli à nouveau la liste des imprimantes disponibles dans l'ordinateur
